/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameii;

import java.awt.Color;
import java.lang.String;

/**
 *
 * @author Phavour
 */
public final class GamePanel extends javax.swing.JFrame {

    /**
     * Creates new form GamePanel
     */
    private GamePanel() {
        initComponents();
        randomColor();
        viewColor();
        change();
    }
	
	String difficulty;
	
	/*
	*Generates color
	*/
    public Color randomColor() {
        int red = (int) (Math.random() * 256);
        int green = (int) (Math.random() * 256);
        int blue = (int) (Math.random() * 256);
        return new Color(red, green, blue);
    }
	
	/*
	*Pushes the generated color into 6 boxes
	*/
    Color[] colorArray = new Color[6];
    public void viewColor() {
        for (int f = 0; f < colorArray.length; f++) {
            colorArray[f] = randomColor();
        }
		
		javax.swing.JPanel[] boxes = new javax.swing.JPanel[6];
        boxes[0] = colorBox1;
        boxes[1] = colorBox2;
        boxes[2] = colorBox3;
        boxes[3] = colorBox4;
        boxes[4] = colorBox5;
        boxes[5] = colorBox6;
		
        for (int x = 0; x < boxes.length; x++) {
            boxes[x].setBackground(colorArray[x]);
        }
//        colorBox1.setBackground(colorArray[0]);
//        colorBox2.setBackground(colorArray[1]);
//        colorBox3.setBackground(colorArray[2]);
//        colorBox4.setBackground(colorArray[3]);
//        colorBox5.setBackground(colorArray[4]);
//        colorBox6.setBackground(colorArray[5]);
        difficulty = "hard";
    }
	
	/*
	*Pushes the generated color into 3 boxes
	*/
	Color[] colorArrayEasy = new Color[3];
	public void viewColorEasy(){
		for (int i = 0; i < colorArrayEasy.length; i++) {
            colorArrayEasy[i] = randomColor();
        }
		
		javax.swing.JPanel[] boxes = new javax.swing.JPanel[3];
        boxes[0] = colorBox1;
        boxes[1] = colorBox2;
        boxes[2] = colorBox3; 
	
        for (int v = 0; v < boxes.length; v++) {
            boxes[v].setBackground(colorArrayEasy[v]);
        }
		
		difficulty = "easy";
	}
	
	/*
	*Randomly selects RGB value to display for hard
	*/
    int selector = 0;
    public void change() {
		selector = (int) (Math.random() * 5);
		String rgbValue = colorArray[selector].toString();
        mainValue.setText("RGB " + rgbValue.substring(14));
		difficulty = "hard";
    }
	
	/*
	Randomly selects RGB value to display for easy
	*/
	int selectorEasy = 0;
	public void changeEasy(){
		selectorEasy = (int) (Math.random() * 2);
		String rgbValueEasy = colorArrayEasy[selectorEasy].toString();
		mainValue.setText("RGB " + rgbValueEasy.substring(14));
		difficulty = "easy";
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        colorBox4 = new javax.swing.JPanel();
        colorBox3 = new javax.swing.JPanel();
        colorBox1 = new javax.swing.JPanel();
        colorBox5 = new javax.swing.JPanel();
        colorBox6 = new javax.swing.JPanel();
        colorBox2 = new javax.swing.JPanel();
        headBox = new javax.swing.JPanel();
        mainValue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        easyBtn = new javax.swing.JLabel();
        hardBtn = new javax.swing.JLabel();
        playAgain = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phav RGB Game 1.0");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 56));

        colorBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBox4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBox4Layout = new javax.swing.GroupLayout(colorBox4);
        colorBox4.setLayout(colorBox4Layout);
        colorBox4Layout.setHorizontalGroup(
            colorBox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorBox4Layout.setVerticalGroup(
            colorBox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        colorBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBox3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBox3Layout = new javax.swing.GroupLayout(colorBox3);
        colorBox3.setLayout(colorBox3Layout);
        colorBox3Layout.setHorizontalGroup(
            colorBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorBox3Layout.setVerticalGroup(
            colorBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        colorBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBox1Layout = new javax.swing.GroupLayout(colorBox1);
        colorBox1.setLayout(colorBox1Layout);
        colorBox1Layout.setHorizontalGroup(
            colorBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorBox1Layout.setVerticalGroup(
            colorBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        colorBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBox5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBox5Layout = new javax.swing.GroupLayout(colorBox5);
        colorBox5.setLayout(colorBox5Layout);
        colorBox5Layout.setHorizontalGroup(
            colorBox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorBox5Layout.setVerticalGroup(
            colorBox5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        colorBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBox6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBox6Layout = new javax.swing.GroupLayout(colorBox6);
        colorBox6.setLayout(colorBox6Layout);
        colorBox6Layout.setHorizontalGroup(
            colorBox6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorBox6Layout.setVerticalGroup(
            colorBox6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        colorBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBox2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBox2Layout = new javax.swing.GroupLayout(colorBox2);
        colorBox2.setLayout(colorBox2Layout);
        colorBox2Layout.setHorizontalGroup(
            colorBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        colorBox2Layout.setVerticalGroup(
            colorBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        headBox.setBackground(new java.awt.Color(18, 30, 49));

        mainValue.setFont(new java.awt.Font("Segoe UI Semilight", 1, 43)); // NOI18N
        mainValue.setForeground(new java.awt.Color(255, 255, 255));
        mainValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout headBoxLayout = new javax.swing.GroupLayout(headBox);
        headBox.setLayout(headBoxLayout);
        headBoxLayout.setHorizontalGroup(
            headBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headBoxLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(mainValue, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        headBoxLayout.setVerticalGroup(
            headBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headBoxLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mainValue, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(224, 224, 255));

        easyBtn.setFont(new java.awt.Font("DigifaceWide", 0, 18)); // NOI18N
        easyBtn.setForeground(new java.awt.Color(204, 102, 0));
        easyBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyBtn.setText("Easy");
        easyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyBtnMouseExited(evt);
            }
        });

        hardBtn.setFont(new java.awt.Font("DigifaceWide", 0, 18)); // NOI18N
        hardBtn.setForeground(new java.awt.Color(153, 0, 0));
        hardBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardBtn.setText("Hard");
        hardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardBtnMouseClicked(evt);
            }
        });

        playAgain.setFont(new java.awt.Font("DigifaceWide", 0, 18)); // NOI18N
        playAgain.setForeground(new java.awt.Color(0, 102, 0));
        playAgain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playAgain.setText("Play Again");
        playAgain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                playAgainMouseMoved(evt);
            }
        });
        playAgain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                playAgainFocusGained(evt);
            }
        });
        playAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playAgainMouseClicked(evt);
            }
        });
        playAgain.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                playAgainPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(playAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(easyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(hardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(easyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(playAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(headBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(headBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(colorBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBox1MouseClicked
        
		switch (difficulty){
			case "hard":
				if(colorArray[selector] == colorArray[0]){
					colorBox1.setBackground(colorArray[0]);
					colorBox2.setBackground(colorArray[0]);
					colorBox3.setBackground(colorArray[0]);
					colorBox4.setBackground(colorArray[0]);
					colorBox5.setBackground(colorArray[0]);
					colorBox6.setBackground(colorArray[0]);
					headBox.setBackground(colorArray[0]);
				}else{
					colorBox1.setBackground(new java.awt.Color(51, 51, 56));
				}
		    break;
			case "easy":
				if(colorArrayEasy[selectorEasy] == colorArrayEasy[0]){
					colorBox1.setBackground(colorArrayEasy[0]);
					colorBox2.setBackground(colorArrayEasy[0]);
					colorBox3.setBackground(colorArrayEasy[0]);
					headBox.setBackground(colorArrayEasy[0]);
				}else{
					colorBox1.setBackground(new java.awt.Color(51, 51, 56));
				}
		    break;
			default:
	    }
    }//GEN-LAST:event_colorBox1MouseClicked

    private void easyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtnMouseExited

    }//GEN-LAST:event_easyBtnMouseExited

    private void hardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardBtnMouseClicked
        headBox.setBackground(new java.awt.Color(18,30,49));
//		hardBtn.setBackground(Color.red);
//		hardBtn.setForeground(Color.white);
		 
		viewColor();
		change();
    }//GEN-LAST:event_hardBtnMouseClicked

    private void easyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtnMouseClicked
        colorBox4.setBackground(new java.awt.Color(51, 51, 56));
        colorBox5.setBackground(new java.awt.Color(51, 51, 56));
        colorBox6.setBackground(new java.awt.Color(51, 51, 56));
		headBox.setBackground(new java.awt.Color(18,30,49));
		 
		viewColorEasy();
		changeEasy();
    }//GEN-LAST:event_easyBtnMouseClicked

    private void colorBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBox2MouseClicked
        
		switch (difficulty){
			case "hard":
				if(colorArray[selector] == colorArray[1]){
					colorBox1.setBackground(colorArray[1]);
					colorBox2.setBackground(colorArray[1]);
					colorBox3.setBackground(colorArray[1]);
					colorBox4.setBackground(colorArray[1]);
					colorBox5.setBackground(colorArray[1]);
					colorBox6.setBackground(colorArray[1]);
					headBox.setBackground(colorArray[1]);
				}else{
					colorBox2.setBackground(new java.awt.Color(51, 51, 56));
				}
		    break;
			case "easy":
				if(colorArrayEasy[selectorEasy] == colorArrayEasy[1]){
					colorBox1.setBackground(colorArrayEasy[1]);
					colorBox2.setBackground(colorArrayEasy[1]);
					colorBox3.setBackground(colorArrayEasy[1]);
					headBox.setBackground(colorArrayEasy[1]);
				}else{
					colorBox2.setBackground(new java.awt.Color(51, 51, 56));
				}
		    break;
			default:
	    }
    }//GEN-LAST:event_colorBox2MouseClicked

    private void colorBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBox3MouseClicked
        
		switch (difficulty){
			case "hard":
				if(colorArray[selector] == colorArray[2]){
					colorBox1.setBackground(colorArray[2]);
					colorBox2.setBackground(colorArray[2]);
					colorBox3.setBackground(colorArray[2]);
					colorBox4.setBackground(colorArray[2]);
					colorBox5.setBackground(colorArray[2]);
					colorBox6.setBackground(colorArray[2]);
					headBox.setBackground(colorArray[2]);
				}else{
					colorBox3.setBackground(new java.awt.Color(51, 51, 56));
				}
		    break;
			case "easy":
				if(colorArrayEasy[selectorEasy] == colorArrayEasy[2]){
					colorBox1.setBackground(colorArrayEasy[2]);
					colorBox2.setBackground(colorArrayEasy[2]);
					colorBox3.setBackground(colorArrayEasy[2]);
					headBox.setBackground(colorArrayEasy[2]);
				}else{
					colorBox3.setBackground(new java.awt.Color(51, 51, 56));
				}
		    break;
			default:
	    }
    }//GEN-LAST:event_colorBox3MouseClicked

    private void colorBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBox4MouseClicked
       
		if(colorArray[selector] == colorArray[3]){
			colorBox1.setBackground(colorArray[3]);
			colorBox2.setBackground(colorArray[3]);
			colorBox3.setBackground(colorArray[3]);
			colorBox4.setBackground(colorArray[3]);
			colorBox5.setBackground(colorArray[3]);
			colorBox6.setBackground(colorArray[3]);
			headBox.setBackground(colorArray[3]);
	   }else{
			colorBox4.setBackground(new java.awt.Color(51, 51, 56));
		}
    }//GEN-LAST:event_colorBox4MouseClicked

    private void colorBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBox5MouseClicked
        
		if(colorArray[selector] == colorArray[4]){
			colorBox1.setBackground(colorArray[4]);
			colorBox2.setBackground(colorArray[4]);
			colorBox3.setBackground(colorArray[4]);
			colorBox4.setBackground(colorArray[4]);
			colorBox5.setBackground(colorArray[4]);
			colorBox6.setBackground(colorArray[4]);
			headBox.setBackground(colorArray[4]);
	   }else{
			colorBox5.setBackground(new java.awt.Color(51, 51, 56));
		}
    }//GEN-LAST:event_colorBox5MouseClicked

    private void colorBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBox6MouseClicked
        
		if(colorArray[selector] == colorArray[5]){
			colorBox1.setBackground(colorArray[5]);
			colorBox2.setBackground(colorArray[5]);
			colorBox3.setBackground(colorArray[5]);
			colorBox4.setBackground(colorArray[5]);
			colorBox5.setBackground(colorArray[5]);
			colorBox6.setBackground(colorArray[5]);
			headBox.setBackground(colorArray[5]);
	   }else{
			colorBox6.setBackground(new java.awt.Color(51, 51, 56));
		}
    }//GEN-LAST:event_colorBox6MouseClicked

    private void playAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playAgainMouseClicked
			headBox.setBackground(new java.awt.Color(18,30,49));
            viewColor();
		    change();
    }//GEN-LAST:event_playAgainMouseClicked

    private void playAgainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playAgainFocusGained

    }//GEN-LAST:event_playAgainFocusGained
 
    private void playAgainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playAgainMouseMoved

    }//GEN-LAST:event_playAgainMouseMoved

    private void playAgainPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_playAgainPropertyChange

    }//GEN-LAST:event_playAgainPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorBox1;
    private javax.swing.JPanel colorBox2;
    private javax.swing.JPanel colorBox3;
    private javax.swing.JPanel colorBox4;
    private javax.swing.JPanel colorBox5;
    private javax.swing.JPanel colorBox6;
    private javax.swing.JLabel easyBtn;
    private javax.swing.JLabel hardBtn;
    private javax.swing.JPanel headBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mainValue;
    private javax.swing.JLabel playAgain;
    // End of variables declaration//GEN-END:variables
}
